apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80            # Port exposed by the service
      targetPort: 3007     # Port on the pod/container
  type: LoadBalancer      # For external access or NodePort for local access
