apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: sanjayvelu14/my-app:latest  # Your image here
        ports:
        - containerPort: 3007            # Your app's port inside the container
        env:
        - name: NODE_ENV
          value: "production"
